version: "3.9"
services:
  rest-api:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app  
    #command: npm run start:dev
  mysql:
    image: mysql
    restart: always
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'

  